#!/bin/bash
set -e

VERSION=$(git rev-parse --short HEAD)

echo "Build hook running for version" $VERSION
docker build \
  --build-arg VCS_REF=`git rev-parse HEAD` \
  --build-arg VCS_URL=`git config --get remote.origin.url` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=$VERSION \
-t $IMAGE_NAME .